### ISSUE TITLE
Extension works only for builds

### ISSUE THREAD

**Issue by thithimos** [carlowahlstedt/SecureFiles_VSTS_Task#1]
Using the extension in a build works as expected. Very useful.
Adding it as a task in a release and using the exact same value for the Provisioning Profile results in:
 ##[error]TypeError: Path must be a string. Received undefined

TFS Version: 2017 Update 3

**Comment by carlowahlstedt** [comment]
Please give me some more time to look into this. I've been very busy and not had the time to come back to it. Thanks.

**Comment by carlowahlstedt** [comment]
Could you post more of your log here? Looking at this and I don't see any difference between build and release that would cause any specific issues.

**Comment by Johant123456** [comment]
I use this exension to build on TFS2018 on Prem.
I get this error : "##[error]Error: unable to verify the first certificate" 
Any idea what goes wrong or any workaround?

**Comment by manoj-kumar1** [comment]
Provisioning Profile field should take "Secure File Name". The name which we use for adding secure file.
![image](https://user-images.githubusercontent.com/5748980/52407465-636e3880-2af6-11e9-963a-afd85f33ac9d.png)

In TFS2017 (hosted) release pipeline, it gives following error:
##[error]TypeError: Path must be a string. Received undefined

Is this issue resolved?? Thanks.

**Comment by carlowahlstedt** [comment]
Honestly, I didn't have enough info previously and I just don't have the time right now. I welcome a PR though. 😁

**Comment by carlowahlstedt** [comment]
please see Microsoft's task now: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops
