### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by Johant123456** [carlowahlstedt/SecureFiles_VSTS_Task#2]
I use TFS2018-3 on Prem.
I get this error when i tryp to access a secure file: "##[error]Error: unable to verify the first certificate"
Any idea what goes wrong or any workaround?

**Comment by carlowahlstedt** [comment]
Please use microsoft's task now: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops
